### PR TITLE
Add support for deploying to Google Cloud

### LINKED ISSUE #40: Setup deployment for GCloud or Heroku
We should make it easy to deploy the current setup to at least one of the above.

### PR DESCRIPTION
**Pull request by addyosmani**
This set of changes enables us to push to Node.js on Cloud. I've successfully pushed app-shell to https://app-shell.appspot.com/ using this setup. Fixes #40. 

r: @gauntface

### CODE REVIEW

**Comment by gauntface** [comment]
LGTM nice work.

**Comment by addyosmani** [comment]
giphy 1

**Comment by jeffposnick** [comment]
Now I regret not squatting on that public App Engine instance name :smile:

**Comment by addyosmani** [comment]
:laughing:

**Pull request merged**
